name: Check links

on:
  schedule:
    - cron: '30 2 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Check Markdown links
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --no-progress
            --verbose
            --exclude '^/'
            './docs/**/*.md'
            './blog/**/*.md'
          fail: true
